eureka:
  client:
    register-with-eureka: false
server:
  port: 8093
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: http://localhost:8091
          predicates:
            - Path=/authentication/**
        - id: parameterization
          uri: http://localhost:8090
          predicates:
            - Path=/parameterization/**
        - id: care-plan
          uri: http://localhost:8092
          predicates:
            - Path=/care-plan/**
management:
  tracing:
    sampling:
      probability: 1.0